version: "2.3"

services:
  docker-host:
    image: sbeliakou/playpit-labs:docker
    container_name: docker-host
    hostname: docker-host
    volumes:
      - docker_root:/var/lib/docker
      - ~/docker:/workspace/
    tmpfs:
      - /run
      - /tmp
    ports:
      - 80:80
      - 8080:8080
      - 8022:8022
      - 8081:8081
      - 9090:9090
      - 10080-10100:10080-10100
      - 32768-32800:32768-32800
    environment:
      TRAINING: "docker"
    labels:
      project: ${PWD}
      training: docker
      lab: yes
    cpu_count: 1
    privileged: true
    network_mode: bridge

volumes:
  docker_root:
    name: docker_root
